name: efijuma_app
description: efiJuma app for GADS 2020

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#packages here
  cupertino_icons: ^1.0.0
  firebase_database: ^3.1.1 #^
  geolocator: ^5.3.0  #^
  permission_handler: ^3.1.0 #^
#  firebase_storage: ^3.0.8
#  firebase_core: ^0.4.0
#  cloud_functions: ^0.5.0
  image_picker:
#  file_picker: 1.4.3+1
  path_provider:
  http: 0.12.0 #+4
#  firebase_messaging: ^5.1.2
  get_it: ^1.0.3+2 #^
  url_launcher: ^5.0.3  #^


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/call_agent.png
    - assets/images/support_agent.jpg
    - assets/images/splash_essenkiosk.png
    - assets/images/buyer_avatar.png
    - assets/images/agent_manage_farmData.png
    - assets/images/agent_manage_userData.png
    - assets/images/logo.png
    - assets/splash_essenkiosk.png
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700